### ISSUE TITLE
List of things ToDo

### ISSUE THREAD

**Issue by eabase** [eabase/mt4pycon#1]
Here I leave a list of things yet needed to fix.

- [ ] Fix (or check) default (pip) installation paths for the scripts
- [ ] Fix *double run* problem/bug, when data in MT Terminal is not yet available.
- [ ] Fix **`ModuleNotFoundError: No module named 'clr'`** error, when running from powershell after (pip install).

```
Traceback (most recent call last):
  File "C:\Python38\Scripts\con2mtapi.py", line 93, in <module>
    import clr
ModuleNotFoundError: No module named 'clr'
```

- [ ] Update requirements for Python `3.10+`
- [ ] Update README with:
    - [ ]  link to [`pyreadline3`](https://github.com/pyreadline3/pyreadline3), since the original one does not work for Py3.10+.
    - [ ] Link to original repo
    - [ ] add/fix missing gif video
    - [ ] fix local install command. `pip install -e ./`
- [ ] Update mt5api from original repo.
- [ ] Fix pypi info by adding fulltext to setup files
- [ ] add badge's
- [ ] add coloring to output
